### ISSUE TITLE
iconfont.scss contains 'undefined' and nothing else

### ISSUE THREAD

**Issue by jabyrd3** [HaoyCn/iconfont-plugin-webpack#1]
Hi,

The iconfonts are generated and written where I expected, but the generated scss file has no contents, just undefined.

I followed the example exactly, any advice would be appreciated.

**Comment by HaoyCn** [comment]
Did you set the `cssTemplate` property? There is a built-in function to generate SCSS contents, so if you override the prop, the contents are determined by your own function.

**Comment by jabyrd3** [comment]
I figured that function out right after i opened the issue, sorry to bug you! Thanks for writing this btw, it's the only one i've found that works well with webpack 2.

**Comment by HaoyCn** [comment]
You're always welcome to open issues once you find any problems. Have a good day!

**Comment by ohvitorino** [comment]
I also had this problem, maybe the documentation is not so clear :)
