### ISSUE TITLE
how i can generate only css?

### ISSUE THREAD

**Issue by Venegrad** [HaoyCn/iconfont-plugin-webpack#10]
Hi there. Can i generate only css, withot scss? Or Stylus, or custom template for include in stylus? if yes how?

**Comment by Venegrad** [comment]
Can i use custom template, if yes, can u share example?

**Comment by HaoyCn** [comment]
To make a css file, set `options.dest.css` end up with `.css`.
To generate the content inside the css file, use `option.cssTemplate`. [Here can be an example](https://github.com/HaoyCn/iconfont-plugin-webpack/blob/master/src/template.js).
