### ISSUE TITLE
folder

### ISSUE THREAD

**Issue by siper15** [HaoyCn/iconfont-plugin-webpack#12]
When i create font, It is possible to add some svg in multiple folders ?

**Comment by HaoyCn** [comment]
I assume that you want the plugin to support option.src to be an Array. Don’t you?

**Comment by siper15** [comment]
I have several svgs picture in different subdirectories and i would like the plugin to be able to get svg from each subdirectories. Is it possible ?

**Comment by HaoyCn** [comment]
Yes. The plugin supports directories as well. But it seems that the current version is a bit buggy. Will fix it.

**Comment by HaoyCn** [comment]
**v1.1.3** will work for you. The [demo](https://github.com/HaoyCn/iconfont-plugin-webpack/tree/master/demo) is updated too.

**Comment by siper15** [comment]
it works perfectly. Thanks ^^

**Comment by HaoyCn** [comment]
Nice. I'm closing the issue then.
