### ISSUE TITLE
How to override default template options?

### ISSUE THREAD

**Issue by tjheffner** [HaoyCn/iconfont-plugin-webpack#7]
Thank you for this great iconfont plugin! I'm curious how I can go about overriding default template values (specifically $icon-prefix) without passing an entirely new template into the cssTemplate() function. Is this possible? 

Any changes I make to the generated file obviously do not persist, as the file gets regenerated on subsequent compiles, and I'm not seeing options that can be passed in to override as part of the webpack config, although I might just be blind. Any help would be appreciated.

edit: alternatively, if there are any options to generate the $__iconfont__data map to its own file, without the rest of the sass config vars, mixins, etc, that would work for my use case also.

**Comment by tjheffner** [comment]
Ultimately I just copied template.js to a new local file, and put in an empty `` for the const TEMPLATE with no other changes, and I get a file solely consisting of the $__iconfont__data map. Sorry for the unnecessary issue, thanks again for this great implementation!

**Comment by gromen** [comment]
Could you tell me how to override default template? I would like to change iconfont paths to one level lower (like this `../fonts/`) . When I am starting to watch files with webpack, it's regenerating afresh template, adding default path to fonts directory (`../../fonts`) . How to use cssTemplate option ? What should be in function ? Thanks in advance!

**Comment by HaoyCn** [comment]
@gromen It's easy to get started with cssTemplate option. Just see the [built-in default function](https://github.com/HaoyCn/iconfont-plugin-webpack/blob/master/src/template.js) here.

By the way, the default template uses scss variable `$create-font-face` to determine whether to generate `@font-face` rule. That is, you can just disable it and write your own rule. For example:

```scss
$create-font-face: false;

@font-face {
  // write your own rules
}

@import 'path/to/the/generated/scss-file';
```

**Comment by gromen** [comment]
@HaoyCn thank you for your response!:) I'll try later and I'll give you a reply.

**Comment by gromen** [comment]
> @gromen It's easy to get started with cssTemplate option. Just see the [built-in default function](https://github.com/HaoyCn/iconfont-plugin-webpack/blob/master/src/template.js) here.
> 
> By the way, the default template uses scss variable `$create-font-face` to determine whether to generate `@font-face` rule. That is, you can just disable it and write your own rule. For example:
> 
> ```css-scss
> $create-font-face: false;
> 
> @font-face {
>   // write your own rules
> }
> 
> @import 'path/to/the/generated/scss-file';
> ```



> @HaoyCn thank you for your response!:) I'll try later and I'll give you a reply.

Ok, Icons are working overriding generated @fontface, thanks. I have one more question @HaoyCn: How to override scss `@if` statement from your generated template ? Should I use `cssTemplate` property ? If yes how to use it ?
I would like to override this:

```
@if $create-icon-classes == true {
  .#{$icon-common-class} {
    font-style: normal;
    font-weight: 400
    @each $icon, $content in map-get($__iconfont__data, "myWorldIcons") {
      &.#{$icon-prefix}#{$icon}:before {
        font-family: "myWorldIcons";
        content: iconfont-item("myWorldIcons/#{$icon}");
      }
    }
  }
}
```
and get class selector only `.icon-name` instead of `.icon.name`
