### ISSUE TITLE
Webpack 4 deprecation warnings due to dependency: run-plugin-webpack

### ISSUE THREAD

**Issue by illepic** [HaoyCn/iconfont-plugin-webpack#9]
This package works great, but does cause a deprecation warning due to the `run-plugin-webpack` package using an out of date webpack method:

![capto_capture 2018-04-03_08-22-37_](https://user-images.githubusercontent.com/295127/38259195-4b23d978-3719-11e8-8170-290dac9218fa.png)

Issue opened against https://github.com/HaoyCn/run-plugin-webpack as well: https://github.com/HaoyCn/run-plugin-webpack/issues/1

**Comment by HaoyCn** [comment]
Sorry for the late reply. Updating the plugin to v1.1.2 should fix this issue. I hope you have a good day.
